version: "1.0.0"
services:
  #kalah-game-backend:
  #  image: caoguzelmas/kalah-game-backend:0.3
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - mongo-db
  #    - mongo-express
  #  environment:
  #    MONGODB_CONNECTION_STRING: mongodb://kalah-player:pwd123@localhost:27017
  #    MONGODB_USERNAME: kalah-player123
  #    MONGODB_PASSWORD: pwd123
  #    MONGODB_DATABASE: kalah-db
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: kalah-player
      MONGO_INITDB_ROOT_PASSWORD: pwd123
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kalah-player
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd123
      ME_CONFIG_MONGODB_SERVER: mongo-db
      #ME_CONFIG_MONGODB_URL: mongodb://kalah-player:pwd123@mongo:27017/?authSource=admin
#  kalah-game-frontend:
#    image: caoguzelmas/kalah-game-frontend:0.2
##    ports:
##      - "4200:4200"
#    depends_on:
#      - kalah-game-backend
#    environment:
#      APP_KEY: TEST123
