version: "1.0.0"
services:
  #kalah-game-backend:
  #  image: caoguzelmas/kalah-game-backend:0.3
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - mongo-db
  #    - mongo-express
  #  environment:
  #    MONGODB_CONNECTION_STRING: mongodb://admin:password@localhost:27017
  mongo:
    image: mongo
    #container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: kalah-db
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    #ports:
    #  - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#  kalah-game-frontend:
#    image: caoguzelmas/kalah-game-frontend:0.2
##    ports:
##      - "4200:4200"
#    depends_on:
#      - kalah-game-backend
#    environment:
#      APP_KEY: TEST123
