version: "1.0.0"
services:
  kalah-game-backend:
    image: caoguzelmas/kalah-game-backend:0.4
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo-db
      - mongo-express
    environment:
      MONGODB_CONNECTION_STRING: mongodb://mongo-db/kalah-db
      MONGODB_USERNAME: kalah-player123
      MONGODB_PASSWORD: pwd123
      MONGODB_DATABASE: kalah-db
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: kalah-player
      MONGO_INITDB_ROOT_PASSWORD: pwd123
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kalah-player
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd123
      ME_CONFIG_MONGODB_SERVER: mongo-db