  version: "1.0.0"
  services:
#    kalah-game-backend:
#      image: caoguzelmas/kalah-game-backend
#      ports:
#     2   - "8080:8080"
#      depends_on:
#        - mongo-db
#        - express
    mongo-db:
      image: mongo
      container_name: mongo-db
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: kalah-db
      ports:
        - "27017:27017"
    mongo-express:
      image: mongo-express
      restart: always
      depends_on:
        - mongo-db
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_SERVER: mongo-db
